### ISSUE TITLE
Feature suggestion: Image Manipulation to read/add/change/remove JPEG metadata

### ISSUE THREAD

**Issue by digitall-it** [spatie/.github#7]
I would like to write a new Image manipulation to work on JPEG metadata data (read/write EXIF/IPTC, etc. without recompression) using external binaries. I was wondering if extending Image was the right approach to it, or if I should separate that into something different. Most PHP image manipulation packages have no more than basic metadata reading features and the user is left on his own. EXIF/IPTC writing on manipulated image is a mandatory requirement of my project so I am not asking if that is a good or useful idea (nine of out of ten times you just want to strip everything out to lower the file payload). 
I am indeed asking 
- if you think extending Spatie/Image is a good choice
- any suggestions on approaching the extension process
- any suggestions on the actual manipulation process, I was thinking about invoking [ExifTool](https://exiftool.org) which seems to be very powerful and has support for Mac, Linux and Windows

**Comment by freekmurze** [comment]
Could be nice to have on spatie/image. Feel free to send a PR. If the API is clean, it doesn't involve too much code, tests are present, and docs are updated, I'll consider merging it in!

Unfortunately, I corrently don't have the time to assist with this.
